FROM python:3.6
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install netcat
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=settings.prod
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
RUN pip install gunicorn
ADD shell/wait-for.sh /code/shell/wait-for.sh
ADD manage.py /code/
ADD beans /code/beans
ADD settings /code/settings
ADD accountants /code/accountants
ADD web /code/web
