FROM python:3.6
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install netcat
RUN pip install --upgrade pip
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=settings.dev
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
